### ISSUE TITLE
Scrapely parses the given page based on the first matched template

### ISSUE THREAD

**Issue by HeshamElkhatib** [nabilm/scrapely#2]
If the given page matches more than one template 
It parses the given page based on the first matched template not the most similar one to the given page.
We need to return the item with maximum populated attributes if even the maximum one doesn't have all its attribute populated.

**Comment by nabilm** [comment]
Fixed by 889c721124cae0b3bd94d6346e19fd4fdf8b45bd & c6fa64c74473e71ba050e00f5f871b6b3b1f0cd6

**Comment by HeshamElkhatib** [comment]
We need to return the maximum extracted data even if not all its attributes are populated.

**Comment by nabilm** [comment]
fixed by 59298a91829da3b239fe18865de5c92dd01425d2
